spring.application.name=TaskHive

spring.datasource.url=jdbc:postgresql://localhost:5432/taskhive
spring.datasource.username=c0nf1dxnt
spring.datasource.password=

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate